plugins:
  - jekyll-gist
  
  source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'github-pages'
end

<div class='jekyll-twitter-plugin' align="center">
    {% twitter https://twitter.com/anaik96 maxwidth=500 limit=5 %}
</div>
